# Generated by Django 4.0.2 on 2022-03-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
