# Generated by Django 4.0.2 on 2022-03-12 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pageName', models.CharField(max_length=70)),
                ('pageCat', models.CharField(max_length=70)),
                ('pagePublishDate', models.DateField()),
            ],
        ),
    ]
